### ISSUE TITLE
Unable to install Drupal module

### ISSUE THREAD

**Issue by mzico** [GluuFederation/drupal-oxd-module#1]
Downloaded module from 'https://github.com/GluuFederation/drupal-oxd-module/blob/master/gluu_sso.tar.gz?raw=true' 

Drupal admin panel is throwing below error: 

![screenshot_6](https://cloud.githubusercontent.com/assets/7156097/23343801/b70d36e4-fc36-11e6-9e31-e45047e4e233.png)

**Comment by karapetyan88** [comment]
done
